In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('../Documents/Github/NOVO/train.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
#Change the array to numpy
data= np.array(data)

#m amount of rows, n amount of features +1
m, n = data.shape
np.random.shuffle(data)

#Spliting data
data_dev= data[0:1000].T
Y_dev= data_dev[0]
X_dev= data_dev[1:n]

data_train = data[1000:m].T
Y_train= data_train[0]
X_train= data_train[1:n]

In [4]:
X_train[:,0].shape

(784,)

In [5]:
def init_params():
    W1= np.random.rand(10,784) -0.5
    b1= np.random.rand(10,1) - 0.5
    W2= np.random.rand(10,10) -0.5
    b2= np.random.rand(10,1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z)/np.sum(np.exp(Z))

def forward_prop(W1, b1, W2, b2, X):
    Z1= W1.dot(X) + b1
    A1= ReLU(Z1)
    Z2= W2.dot(A1) + b2
    A2= softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1= W1 - alpha + dW1
    b1= b1 - alpha + db1
    W2= W2 - alpha + dW2
    b2= b2 - alpha + db2
    return W1, b1, W2, b2

In [6]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2= forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2= backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2= update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2



In [7]:
W1, b1, W2, b2= gradient_descent(X_train, Y_train, 100, 0.1)

<ipython-input-5-81f89a4f3a7a>:12: RuntimeWarning: overflow encountered in exp
  return np.exp(Z)/np.sum(np.exp(Z))
<ipython-input-5-81f89a4f3a7a>:12: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(Z)/np.sum(np.exp(Z))


Iteration:  0
[4 4 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09636585365853659
Iteration:  10
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  20
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  30
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  40
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  50
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  60
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  70
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  80
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
Iteration:  90
[0 0 0 ... 0 0 0] [6 4 7 ... 0 4 2]
0.09804878048780488
